config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'comments/create'
  get 'comments/destroy'
  devise_for :accounts

  get "/dashboard" => "accounts#index"
  get "show/:username" => "accounts#show", as: :show

  resources :posts, only: %i[new create show destroy ]
resources :accounts, only: %i[index show edit update], param: :username


  resources :posts do
    resources :likes, only: %i[create destroy]
  end

  resources :accounts do
    post "follow", to: "accounts#follow"
  end

# resources :accounts do
#   resource :follow, only: [:create, :destroy] ,as: :follow
# end

# resources :posts do
# end

resources :posts do
    resources :comments, only: [:create, :destroy]
  resources :comments do
    member do
      get :toggle_replies
    end
  end
end

# resources :posts do
#     post "comments", to: "comments#create"
# end



  root "home#index"
end

app/models/comment.rb
class Comment < ApplicationRecord
  default_scope { order created_at: :desc }
  belongs_to :account
  belongs_to :post

  validates :body, presence: true   

   belongs_to :parent, class_name: "Comment", optional: true
   has_many :replies,class_name: "Comment", foreign_key: "parent_id", dependent: :destroy
     scope :top_level, -> { where(parent_id: nil) }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post

  def create
    @comment = @post.comments.build(comment_params)
    @comment.account = current_account

    if @comment.save
      respond_to do |format|
        format.turbo_stream
        format.html { redirect_to account_path(@post.account.username) }
      end
    else
      respond_to do |format|
        format.turbo_stream { flash[:alert] = "Something went wrong ❌" }
        # format.html { redirect_to account_path(@post.account.username) }
      end
    end
  end

  def destroy
    @comment= Comment.find(params[:id])

    if @comment.account_id== current_account.id
      @comment.destroy
    end

    respond_to do |format|
    format.turbo_stream
    format.html { redirect_back(fallback_location: root_path) }
   end
  end

  def toggle_replies
  @comment = Comment.find(params[:id])
  @post = @comment.post
  @show_replies = params[:hide].blank?  # true if not hiding, false if hiding

  respond_to do |format|
    format.turbo_stream
  end
  end


  private

  def set_post
    @post = Post.find(params[:post_id])
  end

  def comment_params
    params.require(:comment).permit(:body, :parent_id)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper

end

app/views/comments/_comment.html.erb
<div id="comment_<%= comment.id %>" class="p-2 mb-2 ">
  <strong><%= comment.account&.username || "Unknown User" %>:</strong>
    <%= comment.body %>
  <a href="#" class="text-primary small reply-link"
   data-comment-id="<%= comment.id %>"
    onclick="toggleReplies(event, this)">
    Reply
  </a>

  <% if comment.replies.any? %>
    <a href="#" class="text-primary small toggle-replies-link"
     data-comment-id="<%= comment.id %>"
      onclick="toggleReplies(event, this)">
      View All
    </a>
  <% end %>

  <div id="reply-form-<%= comment.id %>" class="mt-2" style="display:none;">
    <%= form_with(model: [comment.post, Comment.new], local: false, html: { class: "reply-form", data: { comment_id: comment.id } }) do |f| %>
      <%= f.hidden_field :parent_id, value: comment.id %>
      <%= f.text_field :body, placeholder: "Write a reply...", class: "form-control mb-2 reply-body" %>
      <%= f.submit "Reply", class: "btn btn-sm btn-primary" %>
    <% end %>
  </div>


        <% if comment.account == current_account %>
<%= button_to post_comment_path(comment.post, comment),
      method: :delete,
      data: { turbo_confirm: "Are you sure?" },
      class: "btn btn-sm btn-danger p-1 d-flex align-items-center justify-content-center" do %>
  <i class="fas fa-trash"></i>
<% end %>
<% end %>

  <div id="comments_<%= comment.id %>" class="replies-section mt-2" style="display:none;">
    <% comment.replies&.each do |reply| %>
      <div class="ms-4 mt-2 p-2 border-start">
         <%= render partial: "comments/comment", locals: { comment: reply } %>
      </div>
    <% end %>
  </div>


</div>

<script>
  function toggleReplies(event, element) {
  event.preventDefault();
  const commentId = element.dataset.commentId;

  if (element.classList.contains("reply-link")) {
    const replyForm = document.getElementById(`reply-form-${commentId}`);
    if (!replyForm) return;

    if (replyForm.style.display === "none" || replyForm.style.display === "") {
      replyForm.style.display = "block";
      element.textContent = "Hide";
    } else {
      replyForm.style.display = "none";
      element.textContent = "Reply";
    }
  }

  if (element.classList.contains("toggle-replies-link")) {
    const repliesSection = document.getElementById(`comments_${commentId}`);
    if (!repliesSection) return;

    if (repliesSection.style.display === "" || repliesSection.style.display === "none") {
      repliesSection.style.display = "block";
      element.textContent = "Hide Replies";
    } else {
      repliesSection.style.display = "none";
      element.textContent = "View All";
    }
  }
}

</script>

app/views/comments/_form.html.erb
<div id="comments_for_post_<%= post.id %>">
<% post.comments.where(parent_id: nil).each do |comment| %>
  <%= render partial: "comments/comment", locals: { comment: comment, post: post } %>
<% end %>

</div>


<%= form_with(model: [post, Comment.new], local: false, id: "new_comment_form_#{post.id}") do |f| %>
  <%= f.hidden_field :parent_id, value: nil %>
  <%= f.text_field :body, 
        placeholder: "Write a comment...", 
        class: "form-control mb-2" %>
  <%= f.submit "Comment", class: "btn btn-sm btn-dark" %>
<% end %>

<script>
document.addEventListener("turbo:submit-end", function(event) {
  
  if (event.target.matches(".reply-form")) {
    event.target.reset();

    // const commentId = event.target.dataset.commentId;
    // if (commentId) {
    //   const form = document.getElementById(`reply-form-${commentId}`);
    //   if (form) form.style.display = "none";
    // }
  }
  
  if (event.target.matches("form[id^='new_comment_form_']")) {
    event.target.reset();
  }
});

</script>

app/views/comments/create.turbo_stream.erb
<% if @comment.parent_id.present? %>
  <!-- Agar reply hai -->
  <%= turbo_stream.replace "comment_#{@comment.parent_id}" do %>
    <%= render partial: "comments/comment", locals: { comment: Comment.find(@comment.parent_id) } %>
  <% end %>
<% else %>
  <!-- Agar normal comment hai -->
  <%= turbo_stream.append "comments_for_post_#{@comment.post.id}" do %>
    <%= render partial: "comments/comment", locals: { comment: @comment } %>
  <% end %>
<% end %>

app/views/comments/destroy.turbo_stream.erb
<%= turbo_stream.remove "comment_#{@comment.id}" %>